- name: conditions #when
  hosts: local
  connection: local
  vars:
    number: 9
  tasks:
  - name: chceking number is lesthen 10 or not
    ansible.builtin.debug:
      when: number < 10 

      msg: "given number {{number}} is less then 10"
    # when: number < 10 